FROM centos:7
MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

RUN yum -y install git epel-release && yum -y install python-pip && yum clean all && rm -rf /var/cache/yum
RUN pip install flask gspread oauth2client

ADD fe.py /tmp
ADD update.py /usr/bin
RUN chmod o+x /usr/bin/update.py

ENTRYPOINT  ["python", "/tmp/fe.py"]
